EvidencijaRadnogVremena/Controllers/MarketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EvidencijaRadnogVremena.Models;

namespace EvidencijaRadnogVremena.Controllers
{
    [System.Web.Mvc.Authorize]
    public class MarketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Markets
        public ActionResult Index()
        {
            return View(db.Markets.ToList());
        }

        // GET: Markets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = db.Markets.Include(m=>m.Radnici).SingleOrDefault(m=>m.MarketId == id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // GET: Markets/Create
        public ActionResult Create()
        {
            return View("MarketForm", new Market());
        }

        // POST: Markets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "MarketId,SifraMarketa,Adresa,Naziv,PonedeljakPocetakRadnogVremena,PonedeljakKrajRadnogVremena,UtorakPocetakRadnogVremena,UtorakKrajRadnogVremena,SredaPocetakRadnogVremena,SredaKrajRadnogVremena,CetvrtakPocetakRadnogVremena,CetvrtakKrajRadnogVremena,PetakPocetakRadnogVremena,PetakKrajRadnogVremena,SubotaPocetakRadnogVremena,SubotaKrajRadnogVremena,NedeljaPocetakRadnogVremena,NedeljaKrajRadnogVremena")] Market market)
        {
            if (!ModelState.IsValid)
            {
                foreach (var prop in ModelState.Where(prop => prop.Value.Errors.Any()))
                {
                    Console.WriteLine(prop.Key, prop.Value.Errors);
                }

                return View("MarketForm", market);
            }
            if (market.MarketId == 0)
            {
                db.Markets.Add(market);
            }
            else
            {
                db.Entry(market).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Markets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = db.Markets.SingleOrDefault(mar => mar.MarketId == id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View("MarketForm", market);
        }

        // POST: Markets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MarketId,SifraMarketa,Adresa,Naziv,PonedeljakPocetakRadnogVremena,PonedeljakKrajRadnogVremena,UtorakPocetakRadnogVremena,UtorakKrajRadnogVremena,SredaPocetakRadnogVremena,SredaKrajRadnogVremena,CetvrtakPocetakRadnogVremena,CetvrtakKrajRadnogVremena,PetakPocetakRadnogVremena,PetakKrajRadnogVremena,SubotaPocetakRadnogVremena,SubotaKrajRadnogVremena,NedeljaPocetakRadnogVremena,NedeljaKrajRadnogVremena")] Market market)
        {
            if (ModelState.IsValid)
            {
                db.Entry(market).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("MarketForm", market);
        }

        // GET: Markets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = db.Markets.Find(id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // POST: Markets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Market market = db.Markets.Find(id);
            db.Markets.Remove(market);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private List<Market> GetMarketiFromDB()
        {
            return db.Markets.ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EvidencijaRadnogVremena/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EvidencijaRadnogVremena.Models;

namespace EvidencijaRadnogVremena.Controllers
{
    [System.Web.Mvc.Authorize]
    public class WorkersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Workers
        public ActionResult Index()
        {
            var radniks = db.Workers.Include(r => r.Market);
            return View(radniks.ToList());
        }

        // GET: Workers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker radnik = db.Workers.Find(id);
            if (radnik == null)
            {
                return HttpNotFound();
            }
            return View(radnik);
        }

        // GET: Workers/Create
        public ActionResult Create()
        {
            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");
            return View("WorkerForm", new Worker());
        }

        // POST: Workers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "RadnikId,SifraRadnika,ImePrezime,MarketId,Uloga,Pasivan,Password,ConfirmPassword,Boja,Email,Market,Username")] Worker radnik)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa", radnik.MarketId);
                foreach (var prop in ModelState.Where(prop => prop.Value.Errors.Any()))
                {
                    Console.WriteLine(prop.Key, prop.Value.Errors);
                }
                return View("WorkerForm", radnik);
            }

            if (radnik.RadnikId == 0) //Novi radnik
            {
                db.Workers.Add(radnik);

            }
            else // Ažuriranje
            {
                db.Entry(radnik).State = EntityState.Modified;
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Workers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker radnik = db.Workers.Find(id);
            if (radnik == null)
            {
                return HttpNotFound();
            }
            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa", radnik.MarketId);
            return View("Edit", new UpdateWorkerViewModel
            { Market = radnik.Market, Argb = radnik.Argb, Boja = radnik.Boja, Email = radnik.Email, ImePrezime = radnik.ImePrezime, MarketId = radnik.MarketId, Pasivan = radnik.Pasivan, 
                RadnikId = radnik.RadnikId, SifraRadnika = radnik.SifraRadnika, Uloga = radnik.Uloga, Username = radnik.Username }
            );
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Argb,RadnikId,SifraRadnika,ImePrezime,MarketId,Uloga,Boja,Email,Pasivan,Username")] UpdateWorkerViewModel radnik)
        {
            var current = db.Workers.FirstOrDefault(p => p.RadnikId == radnik.RadnikId);
            if (current == null)
                return HttpNotFound();

            if (!ModelState.IsValid)
            {
                ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa", radnik.MarketId);
                foreach (var prop in ModelState.Where(prop => prop.Value.Errors.Any()))
                {
                    Console.WriteLine(prop.Key, prop.Value.Errors);
                }
                return View("Edit", radnik);
            }
            //current.Argb = radnik.Argb;
            current.ConfirmPassword = current.Password;
            current.Email = radnik.Email;
            current.Pasivan = radnik.Pasivan;
            current.SifraRadnika = radnik.SifraRadnika;
            current.ImePrezime = radnik.ImePrezime;
            current.MarketId = radnik.MarketId;
            current.Boja = radnik.Boja;
            db.SaveChanges();
            return RedirectToAction("Index");
            //ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa", radnik.MarketId);
            //return View("Edit", radnik);
        }

        // GET: Workers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker radnik = db.Workers.Find(id);
            if (radnik == null)
            {
                return HttpNotFound();
            }
            return View(radnik);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Worker radnik = db.Workers.Find(id);
            db.Workers.Remove(radnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EvidencijaRadnogVremena/Views/Markets/Delete.cshtml
@model EvidencijaRadnogVremena.Models.Market

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-8"><h2>Da li ste sigurni da želite da izbrišete market?</h2></div>
    <div class="col-4">
        <span class="float-right">
            @Html.ActionLink(" Povratak na listu marketa", "Index", "", new { @class = "btn btn-secondary fa fa-undo" })
        </span>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-4">
        
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SifraMarketa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SifraMarketa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PonedeljakRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PonedeljakRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.UtorakRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UtorakRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.SredaRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SredaRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.CetvrtakRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CetvrtakRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.PetakRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetakRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.SubotaRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubotaRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.NedeljaRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NedeljaRadnoVreme)
            </dd>
        </dl>
    </div>
</div>

<div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value=" Delete" class="btn btn-danger" /> 
    </div>
}
</div>

EvidencijaRadnogVremena/Views/Markets/Details.cshtml
@model EvidencijaRadnogVremena.Models.Market

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-6"><h2>Detalji marketa</h2></div>
    <div class="col-6">
        <span class="float-right">
            @Html.ActionLink(" Povratak na listu marketa", "Index", "", new { @class = "btn btn-secondary fa fa-undo" })
        </span>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-4">
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.SifraMarketa)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SifraMarketa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PonedeljakRadnoVreme)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PonedeljakRadnoVreme)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UtorakRadnoVreme)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.UtorakRadnoVreme)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SredaRadnoVreme)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SredaRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.CetvrtakRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CetvrtakRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.PetakRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetakRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.SubotaRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubotaRadnoVreme)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.NedeljaRadnoVreme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NedeljaRadnoVreme)
            </dd>
        </dl>
        @Html.ActionLink(" Izmeni", "Edit", new { id = Model.MarketId }, new { @class = "btn btn-success fa fa-pencil-square-o" })
    </div>

    <div class="col-md-8">
        <h4>Radnici</h4>
        <table class="table table-hover">
            @foreach (var item in Model.Radnici)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SifraRadnika)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImePrezime)
                    </td>
                    <td>
                        @Html.ActionLink(" Izmeni", "Edit", "Workers", new { id = item.RadnikId }, new { @class = "btn-sm btn-success fa fa-pencil-square-o" })
                        @Html.ActionLink("Detalji", "Details", "Workers", new { id = item.RadnikId }, new { @class = "btn-sm btn-info fa fa-list-alt" })
                        @Html.ActionLink("Obriši", "Delete", "Workers", new { id = item.RadnikId }, new { @class = "btn-sm btn-danger fa fa-trash-o" })
                    </td>
                </tr>
            }
        </table>
    </div>
     
</div>

EvidencijaRadnogVremena/Views/Markets/Index.cshtml
@model IEnumerable<EvidencijaRadnogVremena.Models.Market>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-6"><h2>Spisak marketa</h2></div>
    <div class="col-6">
        <span class="float-right">
            @Html.ActionLink(" Dodaj novi market", "Create", "", new { @class = "btn btn-primary fa fa-plus" })
        </span>
    </div>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SifraMarketa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                Akcije
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SifraMarketa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>

                <td>

                    @*<a href="@Url.Action("Edit", new { id = item.MarketId })" class="btn-sm btn-success">
                            <i class="fa fa-pencil-square-o"></i>
                            <span>
                                <strong>Izmeni</strong>
                            </span>
                        </a>*@

                    @Html.ActionLink(" Izmeni", "Edit", new { id = item.MarketId }, new { @class = "btn-sm btn-success fa fa-pencil-square-o" })
                    @Html.ActionLink(" Detalji", "Details", new { id = item.MarketId }, new { @class = "btn-sm btn-info fa fa-list-alt" })
                    @Html.ActionLink(" Obriši", "Delete", new { id = item.MarketId }, new { @class = "btn-sm btn-danger fa fa-trash-o" })
                </td>
            </tr>
        }
    </tbody>
</table>

EvidencijaRadnogVremena/Views/Markets/MarketForm.cshtml
@model EvidencijaRadnogVremena.Models.Market

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-6"><h2>Detalji marketa</h2></div>
    <div class="col-6">
        <span class="float-right">
            @Html.ActionLink(" Povratak na listu marketa", "Index", "", new { @class = "btn btn-secondary fa fa-undo" })
        </span>
    </div>
</div>

<hr />

@using (Html.BeginForm("Save", "Markets"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.MarketId)

    @Html.ValidationSummary(true, "Molimo, ispravite navedene greške!", new { @class = "text-danger" })

    <div class="form-group row">
        @Html.LabelFor(model => model.SifraMarketa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SifraMarketa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SifraMarketa, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row">
        @Html.Label("Dan", htmlAttributes: new { @class = "control-label font-weight-bold col-md-2" })
        @Html.Label("Početak", htmlAttributes: new { @class = "control-label font-weight-bold col-md-2" })
        @Html.Label("Kraj", htmlAttributes: new { @class = "control-label font-weight-bold col-md-2" })
    </div>
    <div class="form-group row">
        @Html.Label("Ponedeljak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.PonedeljakPocetakRadnogVremena, "{0: HH:mm}", new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.PonedeljakKrajRadnogVremena, "{0: c}", new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.PonedeljakPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.PonedeljakKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Utorak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.UtorakPocetakRadnogVremena, @"{0: hh\:mm}", new { htmlAttributes = new { @class = "form-control", @value = "07:00", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.UtorakKrajRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.UtorakPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.UtorakKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Sreda", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.SredaPocetakRadnogVremena, "{0:HH:mm}", new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.SredaKrajRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.SredaPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.SredaKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Četvrtak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.CetvrtakPocetakRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.CetvrtakKrajRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.CetvrtakPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.CetvrtakKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Petak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.PetakPocetakRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.PetakKrajRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.PetakPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.PetakKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Subota", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.SubotaPocetakRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.SubotaKrajRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.SubotaPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.SubotaKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.Label("Nedelja", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.NedeljaPocetakRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.NedeljaKrajRadnogVremena, new { htmlAttributes = new { @class = "form-control", @type = "time", @step = "300" } })
        </div>
        <div class="col-md-6">
            @Html.ValidationMessageFor(model => model.NedeljaPocetakRadnogVremena, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.NedeljaKrajRadnogVremena, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />
    <div class="form-group row">
        <div class="col-md-offset-2 col-md-2">
            <button type="submit" class="btn btn-primary btn-block">
                <i class="fa fa-save"></i> Sačuvaj
            </button>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}