EvidencijaRadnogVremena/Models/NedeljniPlan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EvidencijaRadnogVremena.Models
{
    public class NedeljniPlan
    {
        public int NedeljniPlanId { get; set; }

        [DisplayName("Datum od")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DatumOd { get; set; }

        [DisplayName("Datum do")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DatumDo { get; set; }

        [NotMapped]
        public string Period { get { return $"{DatumOd.ToShortDateString()} - {DatumDo.ToShortDateString()}"; } }

        [DisplayName("Šifra marketa")]
        public int MarketId { get; set; }

        public virtual Market Market { get; set; }

        public virtual List<DnevniPlan> DnevniPlanovi { get; set; }
    }
}

EvidencijaRadnogVremena/Controllers/NedeljniPlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EvidencijaRadnogVremena.Models;
using EvidencijaRadnogVremena.ViewModel;

namespace EvidencijaRadnogVremena.Controllers
{
    [System.Web.Mvc.Authorize]
    public class NedeljniPlansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET: NedeljniPlans
        public ActionResult Index()
        {
            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");

            var nedeljniVM = new EvidencijaRadnogVremena.ViewModel.NedeljniPlanoviViewModel()
            {
                NedeljniPlanovi = db.NedeljniPlans.ToList(),
                Marketi = new SelectList(db.Markets, "MarketId", "SifraMarketa"),
            };

            return View(nedeljniVM);
        }

        [HttpPost]
        public ActionResult Index(int? MarketId)
        {
            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");
            var nedeljniPlan = db.NedeljniPlans.Where(r => r.MarketId == MarketId).ToList();
            return View(nedeljniPlan);
        }

        // GET: NedeljniPlans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NedeljniPlan nedeljniPlan = db.NedeljniPlans.Find(id);
            if (nedeljniPlan == null)
            {
                return HttpNotFound();
            }
            return View(nedeljniPlan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NedeljniPlanoviViewModel nedeljniPlanViewModel)
        {
            var radnici = db.Workers.Where(rad => rad.MarketId == nedeljniPlanViewModel.MarketId).ToList();
            var nedeljniPlan = new NedeljniPlan();
            nedeljniPlan.MarketId = nedeljniPlanViewModel.MarketId;
            nedeljniPlan.Market = db.Markets.Single(mar => mar.MarketId == nedeljniPlan.MarketId);
            nedeljniPlan.DatumOd = GetPrviDanUNedelji(nedeljniPlanViewModel.Nedelja);
            nedeljniPlan.DatumDo = nedeljniPlan.DatumOd.AddDays(6);
            nedeljniPlan.DnevniPlanovi = new List<DnevniPlan>();
            for (DateTime datum = nedeljniPlan.DatumOd; datum < nedeljniPlan.DatumDo; datum = datum.AddDays(1))
                foreach (var radnik in nedeljniPlan.Market.Radnici)
                    nedeljniPlan.DnevniPlanovi.Add(new DnevniPlan() { RadnikId = radnik.RadnikId, Datum = datum, NedeljniPlan = nedeljniPlan, PlaniranPocetakRada = DateTime.Now, 
                        PlaniranKrajRada = DateTime.Now, PlaniranPocetakPauze = DateTime.Now, PlaniranKrajPauze = DateTime.Now
                    });
            nedeljniPlan.DnevniPlanovi.OrderBy(dp => dp.Datum).ThenBy(dp => dp.NedeljniPlan.MarketId).ThenBy(dp => dp.RadnikId);

            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");
            ViewBag.ListaRadnika = new SelectList(db.Workers, "RadnikId", "SifraRadnika");
            return View("NedeljniPlanForm", nedeljniPlan);
        }


        //// POST: NedeljniPlans/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "NedeljniPlanId,DatumOd,DatumDo,MarketId")] NedeljniPlan nedeljniPlan)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.NedeljniPlans.Add(nedeljniPlan);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");
        //    return View(nedeljniPlan);
        //}

        // GET: NedeljniPlans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NedeljniPlan nedeljniPlan = db.NedeljniPlans.Include(np => np.DnevniPlanovi).Include(np => np.Market).Include(np => np.Market.Radnici).SingleOrDefault(x => x.NedeljniPlanId == id);

            if (nedeljniPlan == null)
            {
                return HttpNotFound();
            }
            nedeljniPlan.DnevniPlanovi.OrderBy(dp => dp.Datum).ThenBy(dp => dp.NedeljniPlan.MarketId).ThenBy(dp => dp.RadnikId);

            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa", nedeljniPlan.MarketId);
            return View("NedeljniPlanForm", nedeljniPlan);
        }

        // POST: NedeljniPlans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NedeljniPlanId,DatumOd,DatumDo,MarketId")] NedeljniPlan nedeljniPlan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nedeljniPlan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");
            return View("NedeljniPlanForm", nedeljniPlan);
        }

        public ActionResult AddWorker(int id)
        {
            var nedeljniPlan = db.NedeljniPlans.Single(np => np.NedeljniPlanId == id);
            if (ModelState.IsValid)
            {
                db.Entry(nedeljniPlan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa");
            return View("NedeljniPlanForm", nedeljniPlan);
        }

        // POST: Workers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save([Bind(Include = "NedeljniPlanId,DatumOd,DatumDo,MarketId,DnevniPlanovi")]NedeljniPlan nedeljniPlan)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.MarketId = new SelectList(db.Markets, "MarketId", "SifraMarketa", nedeljniPlan.MarketId);
                foreach (var prop in ModelState.Where(prop => prop.Value.Errors.Any()))
                {
                    Console.WriteLine(prop.Key, prop.Value.Errors);
                }
                return View("NedeljniPlanForm", nedeljniPlan);
            }

            if (nedeljniPlan.NedeljniPlanId == 0) //Novi nedeljni plan
            {
                db.NedeljniPlans.Add(nedeljniPlan);

            }
            else // Ažuriranje
            {
                foreach (var dp in nedeljniPlan.DnevniPlanovi)
                    db.Entry(dp).State = EntityState.Modified;
                    //if (!TryUpdateModel(dp))
                    //{ 
                    //}
                    //db.Set<NedeljniPlan>().AddOrUpdate(nedeljniPlan);
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: NedeljniPlans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NedeljniPlan nedeljniPlan = db.NedeljniPlans.Find(id);
            if (nedeljniPlan == null)
            {
                return HttpNotFound();
            }
            return View(nedeljniPlan);
        }

        // POST: NedeljniPlans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NedeljniPlan nedeljniPlan = db.NedeljniPlans.Find(id);
            db.NedeljniPlans.Remove(nedeljniPlan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private static DateTime GetPrviDanUNedelji(string nedelja)
        {
            System.Text.RegularExpressions.Regex parseRegex = new System.Text.RegularExpressions.Regex(@"^(?<year>\d{4})-W?(?<week>\d{2})$");
            DateTime date = DateTime.Now;
            var match = parseRegex.Match(nedelja);
            if (match.Success)
            {
                var year = int.Parse(match.Groups["year"].Value);
                var week = int.Parse(match.Groups["week"].Value);
                date = FirstDateOfWeekISO8601(year, week);
            }

            return date;
        }

        public static DateTime FirstDateOfWeekISO8601(int year, int weekOfYear)
        {
            DateTime jan1 = new DateTime(year, 1, 1);
            int daysOffset = DayOfWeek.Thursday - jan1.DayOfWeek;

            // Use first Thursday in January to get first week of the year as
            // it will never be in Week 52/53
            DateTime firstThursday = jan1.AddDays(daysOffset);
            var cal = System.Globalization.CultureInfo.CurrentCulture.Calendar;
            int firstWeek = cal.GetWeekOfYear(firstThursday, System.Globalization.CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);

            var weekNum = weekOfYear;

EvidencijaRadnogVremena/Views/NedeljniPlans/Create.cshtml
@model EvidencijaRadnogVremena.Models.NedeljniPlan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>NedeljniPlan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DatumOd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumOd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumOd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumDo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarketId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@{var items = Model.DnevniPlanovi;}
<table>
    @for (int i = 0; i < items.Count(); i++)
    {
        @*@{var item = items[i];}*@

        <tr>
            <td>
                Test
            </td>
            @{i++;}

            @if (i < items.Count())
            {
                <td>
                    @Html.EditorFor(model => model.DnevniPlanovi[i].Datum, new { htmlAttributes = new { @class = "form-control" } })

                </td>
            }
            @{i++;}

            @if (i < items.Count())
            {
                <td>
                    @Html.Raw(items[i].Datum)
                </td>
            }
        </tr>
    }
</table>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EvidencijaRadnogVremena/Views/NedeljniPlans/Index.cshtml
@model EvidencijaRadnogVremena.ViewModel.NedeljniPlanoviViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<div class="row">
    <div class="col-6"><h2>Nedeljni rasporedi</h2></div>
</div>



@using (Html.BeginForm("Create", "NedeljniPlans"))
{
    @Html.AntiForgeryToken()

    <div>@Html.DropDownListFor(m => m.MarketId, Model.Marketi, "Izaberite market", new { @class = "form-control" })</div>
    <br />

    <div>@Html.EditorFor(m => m.Nedelja, new { htmlAttributes = new { type = "week", @class = "form-control" } }) </div>
    <br />

    <div class="form-group row">
        <div class="col-md-offset-6 col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
                <i class="fa fa-save"></i> Dodaj novi nedeljni raspored
            </button>
        </div>
    </div>

    <br />
}

<input class="form-control" id="myInput" type="text" placeholder="Pretraga...">
<br>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NedeljniPlanovi.FirstOrDefault().DatumOd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NedeljniPlanovi.FirstOrDefault().DatumDo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NedeljniPlanovi.FirstOrDefault().Market.SifraMarketa)
            </th>
            <th>Akcije</th>
        </tr>
    </thead>
    <tbody id="myTable">
        @foreach (var item in Model.NedeljniPlanovi)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumOd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumDo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Market.SifraMarketa)
                </td>
                <td>
                    @Html.ActionLink(" Izmeni", "Edit", new { id = item.NedeljniPlanId }, new { @class = "btn-sm btn-success fa fa-pencil-square-o" })
                    @Html.ActionLink(" Detalji", "Details", new { id = item.NedeljniPlanId }, new { @class = "btn-sm btn-info fa fa-list-alt" })
                    @Html.ActionLink(" Obriši", "Delete", new { id = item.NedeljniPlanId }, new { @class = "btn-sm btn-danger fa fa-trash-o" })
                </td>
            </tr>
        }
    </tbody>
</table>

EvidencijaRadnogVremena/Views/NedeljniPlans/NedeljniPlanForm.cshtml
@model EvidencijaRadnogVremena.Models.NedeljniPlan

@{
    ViewBag.Title = "Detalji nedeljnog plana";
}

<style>
    #selectable .ui-selecting {
        background: #3498DB !important;
    }

    table{
        font-size: 10px !important;
        
    }
    th {
        min-width: 100px;
    }
    table.fit td {
        text-align: center;
        font-family:'Courier New'!important;
    }

    .plan {
        max-width: 8px;
        padding: 0px 1px;
        margin: 0px 1px;
    }

    .tscroll {
        overflow-x: scroll;
    }

    .tscroll table th:first-child {
        position: sticky;
        left: 0;
        background-color: #FFFFFF;
    }
</style>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    function calculateColumn(index) {
            var total = 0;
            $('table tr').each(function () {
                var value = $('td input', this).eq(index).attr("value");
                if (value == "Radi")
                    total += 1;
               
            });
        total = total / 2.0;
         $('table tfoot th').eq(index + 1).text('Total: ' + total);
        }

    $.noConflict();
    jQuery(function ($) {
        $('#selectable').selectable({
            filter: "td",
            selected: function (event, ui) {
                var colorWorkType = "#FFFFFF";
                if ($("input[type='radio'].workTypeClass").is(':checked')) {
                    var workType = $("input[type='radio'].workTypeClass:checked").val();
                }
                var el = $(ui.selected);

                $.each(el, function (i, val) {
                    if (workType == "Radi") {
                        var index = el.index();                      
                        //colorWorkType = el.closest('table').find('thead tr th').eq(index + 7).attr("style").split(':')[1].trim();
                        colorWorkType = el.attr("boja");
                    } else if (workType == "NeRadi") {
                        colorWorkType = "#ECF0F1";
                    } else if (workType == "Pauza") {
                        colorWorkType = "#7F8C8D";
                    } else {
                        colorWorkType = "#F1C40F";
                    }
                    el.closest('td').css("background-color", colorWorkType);
                    $('input', val).each(function () {
                        $(this).css("background-color", colorWorkType);
                        $(this).css("color", "#FFFFFF");
                        //$(this).val(workType);
                        $(this).attr("value", workType);
                        //calculateColumn(index-1);
                    });    
                    
                });
            }
        });
    });

    
</script>

<div class="row">
    <div class="col-6"><h2>Detalji nedeljnog plana</h2></div>
    <div class="col-6">
        <span class="float-right">
            @Html.ActionLink(" Povratak na listu", "Index", "", new { @class = "btn btn-secondary fa fa-undo" })
        </span>
    </div>
</div>

<hr />

@{var items = Model.DnevniPlanovi;}
@using (Html.BeginForm("Save", "NedeljniPlans"))
{
    @Html.AntiForgeryToken()
    for (int i = 0; i < Model.DnevniPlanovi.Count; i++)
    {
        @Html.HiddenFor(m => m.DnevniPlanovi[i].DnevniPlanId)
    }
    for (int i = 0; i < Model.DnevniPlanovi.Count; i++)
    {
        @Html.HiddenFor(m => m.DnevniPlanovi[i].Datum)
    }
    for (int i = 0; i < Model.DnevniPlanovi.Count; i++)
    {
        @Html.HiddenFor(m => m.DnevniPlanovi[i].RadnikId)
    }
    for (int i = 0; i < Model.DnevniPlanovi.Count; i++)
    {
        @Html.HiddenFor(m => m.DnevniPlanovi[i].NedeljniPlanId)
    }
    @Html.HiddenFor(m => m.NedeljniPlanId)
    @Html.HiddenFor(m => m.DatumOd)
    @Html.HiddenFor(m => m.DatumDo)
    @Html.HiddenFor(m => m.MarketId)
    @Html.HiddenFor(m => m.Market)

    <div class="form-group row">
        @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.MarketId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Market.SifraMarketa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Market.SifraMarketa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-primary">
                    <input type="radio" class="workTypeClass" name="workType" value="Radi" checked="checked"> Radi
                </label>
                <label class="btn btn-primary">
                    <input type="radio" class="workTypeClass" name="workType" value="NeRadi"> Ne radi
                </label>
                <label class="btn btn-primary">
                    <input type="radio" class="workTypeClass" name="workType" value="Pauza"> Pauza
                </label>
                <label class="btn btn-primary">
                    <input type="radio" class="workTypeClass" name="workType" value="Odmor"> Odmor
                </label>
            </div>
        </div>
        <div class="col-md-4">
            <span class="float-right">
                @Html.ActionLink(" Dodaj zamenu", "AddWorker", "NedeljniPlans", new { id = Model.NedeljniPlanId }, new { @class = "btn btn-primary fa fa-plus-square" })
            </span>
        </div>
    </div>
    <br />

    <div class="row tscroll">
        <div class="col-md-12">
            <table id="selectable" class="table table-bordered ui-selectable fit">
                <thead>
                    @{var brojRadnika = Model.DnevniPlanovi.Count / 6;}
                    <tr>
                        <th scope="col"></th>
                        @for (DateTime datum = Model.DatumOd; datum < Model.DatumDo; datum = datum.AddDays(1))
                        {
                            <th scope="col" colspan=@brojRadnika>
                                @datum.DayOfWeek - @datum.ToShortDateString()
                            </th>
                        }
                    </tr>

                    <tr>
                        <th scope="row"></th>
                        @for (int j = 0; j < 6; j++)
                        {
                            for (int i = 0; i < brojRadnika; i++)
                            {
                                var c = @Model.Market.Radnici[i].Boja;
                                var radnik = @Model.Market.Radnici.Single(r => r.RadnikId == Model.DnevniPlanovi[i].RadnikId).ImePrezime;
                                string col = $"#{c.R:X2}{c.G:X2}{c.B:X2}";
                                <th scope="row" style="background-color: @col; color:#FFFFFF">@radnik</th>
                            }
                        }
                    </tr>

                </thead>
                <tbody>
                    @*@foreach (var key in dnevniPlan.RadnaVremena.Keys) -----------------OVAJ DEO RADI
        {
            <tr>
                <th class="ui-widget-content ui-selectee">
                    @key.ToString()
                </th>
                @for (int j = 0; j < Model.DnevniPlanovi.Count; j++)
                {
                    <td class="ui-selectee">
                        @Html.EditorFor(model => Model.DnevniPlanovi[j].RadnaVremena[key], new { htmlAttributes = new { @class = "ui-widget-content border-0 plan", @readonly = "readonly" } })
                    </td>
                }
            </tr>
        }*@
                    @{var radnaVremena = typeof(EvidencijaRadnogVremena.Models.DnevniPlan).GetProperties().Where(prop => prop.PropertyType.Name.Equals("TipRadaEnum") && prop.Name.StartsWith("RV"));}
                    @foreach (var rv in radnaVremena)
                    {

                        <tr>
                            <th>
                                @rv.CustomAttributes.First(at => at.AttributeType.Name.Equals("DisplayAttribute")).NamedArguments[0].TypedValue
                            </th>
                            @for (int j = 0; j < Model.DnevniPlanovi.Count; j++)
                            {
                                var c = Model.Market.Radnici.First(rad => rad.RadnikId == Model.DnevniPlanovi[j].RadnikId).Boja;
                                string col = $"#{c.R:X2}{c.G:X2}{c.B:X2}";

                                if (Model.DnevniPlanovi[j][rv.Name] == EvidencijaRadnogVremena.Enums.TipRadaEnum.Radi)
                                {
                                    <td class="ui-selectee" style="background-color: @col; color: #FFFFFF" ; boja=@col>
                                        @Html.EditorFor(model => Model.DnevniPlanovi[j][rv.Name], new { htmlAttributes = new { @class = "ui-widget-content border-0 plan", @readonly = "readonly", style = $"background-color: {col} ; color: #FFFFFF" } })
                                    </td>
                                }
                                else if (Model.DnevniPlanovi[j][rv.Name] == EvidencijaRadnogVremena.Enums.TipRadaEnum.NeRadi)
                                {
                                    <td class="ui-selectee" style="background-color: #ECF0F1; color: #FFFFFF" ; boja=@col>
                                        @Html.EditorFor(model => Model.DnevniPlanovi[j][rv.Name], new { htmlAttributes = new { @class = "ui-widget-content border-0 plan", @readonly = "readonly", style = $"background-color: #ECF0F1; color: #FFFFFF" } })
                                    </td>
                                }
                                else if (Model.DnevniPlanovi[j][rv.Name] == EvidencijaRadnogVremena.Enums.TipRadaEnum.Pauza)
                                {
                                    <td class="ui-selectee" style="background-color: #7F8C8D; color: #FFFFFF" ; boja=@col>
                                        @Html.EditorFor(model => Model.DnevniPlanovi[j][rv.Name], new { htmlAttributes = new { @class = "ui-widget-content border-0 plan", @readonly = "readonly", style = $"background-color:#7F8C8D; color: #FFFFFF" } })
                                    </td>
                                }
                                else
                                {
                                    <td class="ui-selectee" style="background-color: #F1C40F; color: #FFFFFF" ; boja=@col>
                                        @Html.EditorFor(model => Model.DnevniPlanovi[j][rv.Name], new { htmlAttributes = new { @class = "ui-widget-content border-0 plan", @readonly = "readonly", style = $"background-color:#F1C40F; color: #FFFFFF" } })
                                    </td>
                                }

                            }
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>
                            Ukupno sati
                        </th>
                        @for (int i = 0; i < Model.DnevniPlanovi.Count; i++)
                        {
                            <th>
                                @Html.DisplayFor(model => model.DnevniPlanovi[i].BrojSati, new { htmlAttributes = new { @class = "ui-widget-content" } })
                            </th>
                        }

                    </tr>
                </tfoot>                
            </table>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <div class="col-md-offset-2 col-md-2">
            <button type="submit" class="btn btn-primary btn-block">
                <i class="fa fa-save"></i> Sačuvaj
            </button>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}