EvidencijaRadnogVremena/Models/Radnik.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EvidencijaRadnogVremena.Models
{
    public class Radnik
    {
        [Key]
        public int RadnikId { get; set; }
        [DisplayName("Šifra radnika")]
        public string SifraRadnika { get; set; }
        [DisplayName("Ime i prezime")]
        public string ImePrezime { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        [DisplayName("Šifra marketa")]
        public int? MarketId { get; set; }
        public virtual Market Market { get; set; }
        public System.Drawing.Color Boja { get; set; }
        public Enums.UlogaEnum Uloga { get; set; }
    }
}

EvidencijaRadnogVremena/Controllers/RadniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EvidencijaRadnogVremena.Models;

namespace EvidencijaRadnogVremena.Controllers
{
    public class RadniksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Radniks
        public ActionResult Index()
        {
            var radniks = db.Radniks.Include(r => r.Market);
            return View(radniks.ToList());
        }

        // GET: Radniks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Radnik radnik = db.Radniks.Find(id);
            if (radnik == null)
            {
                return HttpNotFound();
            }
            return View(radnik);
        }

        // GET: Radniks/Create
        public ActionResult Create()
        {
            ViewBag.MarketId = new SelectList(db.Marketi, "MarketId", "SifraMarketa");
            return View();
        }

        // POST: Radniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RadnikId,SifraRadnika,ImePrezime,MarketId,Uloga")] Radnik radnik)
        {
            if (ModelState.IsValid)
            {
                db.Radniks.Add(radnik);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MarketId = new SelectList(db.Marketi, "MarketId", "SifraMarketa", radnik.MarketId);
            return View(radnik);
        }

        // GET: Radniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Radnik radnik = db.Radniks.Find(id);
            if (radnik == null)
            {
                return HttpNotFound();
            }
            ViewBag.MarketId = new SelectList(db.Marketi, "MarketId", "SifraMarketa", radnik.MarketId);
            return View(radnik);
        }

        // POST: Radniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RadnikId,SifraRadnika,ImePrezime,MarketId,Uloga")] Radnik radnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(radnik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MarketId = new SelectList(db.Marketi, "MarketId", "SifraMarketa", radnik.MarketId);
            return View(radnik);
        }

        // GET: Radniks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Radnik radnik = db.Radniks.Find(id);
            if (radnik == null)
            {
                return HttpNotFound();
            }
            return View(radnik);
        }

        // POST: Radniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Radnik radnik = db.Radniks.Find(id);
            db.Radniks.Remove(radnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EvidencijaRadnogVremena/Views/Radniks/Create.cshtml
@model EvidencijaRadnogVremena.Models.Radnik

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Radniks"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Radnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SifraRadnika, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SifraRadnika, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SifraRadnika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImePrezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImePrezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImePrezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarketId, "MarketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MarketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MarketId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uloga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Uloga, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Uloga, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Boja, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Boja, new { @class = "jscolor" })
                    @Html.ValidationMessageFor(model => model.Uloga, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Boja, new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(m => m.Boja, new { @type = "color", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Boja, "", htmlAttributes: new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EvidencijaRadnogVremena/Views/Radniks/Details.cshtml
@model EvidencijaRadnogVremena.Models.Radnik

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Radnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Market.SifraMarketa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Market.SifraMarketa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SifraRadnika)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SifraRadnika)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImePrezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImePrezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uloga)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uloga)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Boja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Boja)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RadnikId }) |
    @Html.ActionLink("Back to List", "Index")
</p>